Python/Django/connected/connected/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('person.urls', namespace='person'))
]

Python/Django/connected/person/urls.py
from django.conf.urls import url
from person import views


urlpatterns = (
    url(r'^$', views.index, name='home'),
    url(r'^id(?P<profile_id>\d+)/$', views.details, name='details'),
    url(r'^register/', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^id(?P<profile_id>\d+)/edit/$', views.edit, name='edit'),
    url(r'^id(?P<profile_id>\d+)/del/(?P<post_id>\d+)/$', views.delete_post, name='delete_post'),
    url(r'^id(?P<profile_id>\d+)/add/$', views.add_to_friends, name='add'),
    url(r'^id(?P<profile_id>\d+)/remove/$', views.remove_friend, name='remove'),
)

Python/Django/connected/person/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=150)
    birth_date = models.DateField()
    avatar = models.ImageField(blank=True, upload_to='static/uploads')
    about = models.TextField(blank=True)

    friends = models.ManyToManyField('self', blank=True)

    def __str__(self):
        return  self.name


class WallPost(models.Model):
    receiver = models.ForeignKey(UserProfile)
    sender = models.ForeignKey(UserProfile, related_name="sender")

    pub_date = models.DateTimeField()
    body = models.TextField()

Python/Django/connected/person/forms.py
from django import forms
from django.contrib.auth.models import User
from person.models import UserProfile, WallPost

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		exclude = ('user',)


class WallPostForm(forms.ModelForm):
	class Meta:
		model = WallPost
		fields = ('body', )

Python/Django/connected/person/views.py
from django.shortcuts import render, redirect
from person.models import UserProfile
from person.forms import UserForm, UserProfileForm, WallPostForm
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.cache import cache_control
from django.utils import timezone

# Create your views here.

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def index(request):
    profiles = UserProfile.objects.all()
    return render(request, "index.html", {'profiles': profiles})

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def details(request, profile_id):
    profile = UserProfile.objects.get(id=profile_id)
    wall_posts = profile.wallpost_set.order_by('-pub_date')  # - before pub_date means in descending order
    form = WallPostForm()
    friends = profile.friends.all()
    if request.POST:
        if not request.user.is_authenticated():  # Prevents unauthenticated user from posting
            return redirect('person:login')
        form = WallPostForm(request.POST)
        if form.is_valid():
            wall_post = form.save(commit=False)
            wall_post.receiver = profile
            wall_post.sender = request.user.userprofile
            wall_post.pub_date = timezone.now()
            wall_post.save()
            return  redirect('person:details', profile_id)
        else:
            print("form is not valid")
    return render(request, "details.html", {'profile': profile,
                                            'wall_posts':wall_posts,
                                            'form':form,
                                            'friends':friends})

def register(request):
    if request.POST:
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if profile.avatar:
                profile.avatar = request.FILES['avatar']
            profile.save()
        else:
            print(user_form.errors, profile_form.errors)
        return redirect('person:home')
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
        return render(request, 'register.html', {'user_form': user_form,
                                                 'profile_form': profile_form})

def user_login(request):
        if request.POST:
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return  redirect('person:details', profile_id=user.userprofile.id)
            else:
                return redirect('person:register')

        else:
            return render(request, 'login.html')

def user_logout(request):
    logout(request)
    return redirect('person:home')

def edit(request, profile_id):
    profile = UserProfile.objects.get(id=profile_id)
    profile_form = UserProfileForm(instance=profile)
    if not request.user.is_authenticated():
        return redirect("person:login")
    elif int(profile_id) != request.user.id:
        return  redirect("person:edit", request.user.id)
    else:
        if request.POST:
            profile_form = UserProfileForm(request.POST, request.FILES, instance=profile)
            if profile_form.is_valid():
                profile_form.save()
                return redirect("person:details", profile.id)
            else:
                print("Form is not valid!")
        return render(request, "edit.html", {'profile':profile,
                                         'profile_form':profile_form})

def delete_post(request, profile_id, post_id):
    if not request.user.is_authenticated():
        return redirect('person:login')
    cur_user = request.user.userprofile.id
    profile = UserProfile.objects.get(id=profile_id)
    post = profile.wallpost_set.get(id=post_id)
    if post.sender.id == cur_user or int(profile_id) == cur_user:
        post.delete()
    return redirect('person:details', profile_id)

def add_to_friends(request, profile_id):
    request.user.userprofile.friends.add(UserProfile.objects.get(id=profile_id))
    return redirect('person:details', profile_id)

def remove_friend(request, profile_id):
    request.user.userprofile.friends.remove(UserProfile.objects.get(id=profile_id))
    return redirect('person:details', profile_id)

Python/Django/connected/person/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>connected {% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<b><i>Hello, {% if user.is_authenticated %}{{ user.username }} {% else %}World {% endif %}</i></b>
	<ul>
		<li><a href="{% url 'person:home' %}">Home</a></li>
		{% if user.is_authenticated %}
        <li><a href="{% url 'person:logout' %}">Logout</a></li>
        {% else %}
		<li><a href="{% url 'person:register' %}">Register</a></li>
		<li><a href="{% url 'person:login' %}">Login</a></li>
		{% endif %}
	</ul>
	{% block content %}
	{% endblock %}
</body>
</html>

Python/Django/connected/person/templates/details.html
{% extends 'base.html' %}

{% block title %}
  {{ profile.name }}
{% endblock %}

{% block content %}
  <h2>{{ profile.name }}</h2>
  <i>{{ profile.birth_date }}</i><a href="{% url 'person:edit' profile.id %}">Edit</a> <br>
  {% if profile.avatar %}
	<img src="/{{ profile.avatar }}" alt="" width="15%" height="25%"><br>
  {% else %}
	<p>No image provided</p><br>
  {% endif %}
  <div>{{ profile.about }}</div><br>
<form action="{% url 'person:details' profile.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Post">
</form>

{% if wall_posts %}
    {% for post in wall_posts %}
    <div>
        {% if user.userprofile.id == post.sender.id or proflie.id == user.userprofile.id %}
           <span><a href="{% url 'person:delete_post' profile.id post.id%}">Delete post</a> </span>
        {% endif %}
        <p><b>{{ post.sender }}</b>, said at  <i>{{ post.pub_date }}</i></p><br>
        {{ post.body }}
    </div><br>
    {% endfor %}
{% else %}
    <p>No posts yet!</p>
{% endif %}
  {% if user.is_authenticated and user.userprofile.id != profile.id %}
 {% if not user.userprofile in profile.friends.all%}
    <a href="{% url 'person:add' profile.id %}">Be a friend with {{ profile.name }}</a><br>
  {% else %}
    <p>Already friend</p>
<a href="{% url 'person:remove' profile.id%}">Remove {{ profile.name }} from friends</a>
  {% endif %}
{% endif %}

{% if profile.friends.count > 0 %}
  {% for friend in friends %}
    <a href="{% url 'person:details' friend.id%}">{{ friend.name }}</a><br>
  {% endfor %}
{% else %}
 <p>{{ profile.name }} has no friends yet</p>
{% endif %}
{% endblock %}

Python/Django/connected/person/templates/edit.html
{% extends "base.html" %}
{% block title %}Edit {{profile.name}} {% endblock %}

{% block content %}
<h1>Edit info</h1>
<form action="{% url 'person:edit' profile.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ profile_form.as_p }}
    <input type="submit" value="save changes">
</form>
{% endblock %}

Python/Django/connected/person/templates/index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}
{% block content%}
<b>Hello {% if user.is_authenticated %} {{ user.username }}{%  else %}world! {% endif %}</b>
<ul>
	{% for profile in profiles %}
		<li><a href="{% url 'person:details' profile.id %}">{{ profile.name }}</a></li>
	{% endfor %}
</ul>
{% endblock %}

Python/Django/connected/person/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<h1>Login</h1>
<form action="{% url 'person:login' %}" method="post">
    {% csrf_token %}
    Username: <input type="text" name="username"><br>
    Password: <input type="password" name="password"><br>
    <input type="submit" value="Login">
</form>
{% endblock %}

Python/Django/connected/person/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}
<form action="{% url 'person:register' %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ user_form.as_p }}
	{{ profile_form.as_p }}
	<input type="submit" value="Register">
</form>
{% endblock %}